# Unit 2: Data Analysis using NumPy



# Numpy Statistical Functions : 

# Numpy - Numerical Python library

In [25]:
import numpy as np

In [26]:
# creating an array from a list
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# diamension of an array
print(arr.ndim)

2


In [28]:
# shape of an array
print(arr.shape)

(2, 4)


In [29]:
# type of array
print(type(arr))

<class 'numpy.ndarray'>


In [30]:
# memory location
print(arr.data)

# Statistical function

In [31]:
b = np.array([[54,25,63],[78,1,85],[96,50,10]])
print(b,'\n')

[[54 25 63]
 [78  1 85]
 [96 50 10]] 



In [32]:
b.dtype

dtype('int32')

In [33]:
b.itemsize

4

In [34]:
b.size

9

In [35]:
b.shape

(3, 3)

In [36]:
# convert array of int into float
c = np.array([[54,25,63],[78,1,85],[96,50,10]], dtype = np.float64)
print(c,'\n')
print(c.itemsize)
print(c.dtype)
print(c.size)

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]] 

8
float64
9


In [66]:
# convert array of int into complex
d1 = np.array([[54,25,63],[78,1,85],[96,50,10]], dtype = np.complex64)
print(d1,'\n')
print(d1.itemsize)
print(d1.dtype)
print(d1.size,'\n')

e = np.array([[54,25,63],[78,1,85],[96,50,10]], dtype = np.complex128)
print(e,'\n')
print(e.itemsize)
print(e.dtype)
print(e.size,'\n')

[[54.+0.j 25.+0.j 63.+0.j]
 [78.+0.j  1.+0.j 85.+0.j]
 [96.+0.j 50.+0.j 10.+0.j]] 

8
complex64
9 

[[54.+0.j 25.+0.j 63.+0.j]
 [78.+0.j  1.+0.j 85.+0.j]
 [96.+0.j 50.+0.j 10.+0.j]] 

16
complex128
9 



In [38]:
# sum value of array
print(np.sum(c))

462.0


In [39]:
# sum value along a specified axis
print(np.sum(c, axis = 0)) # columns
print(np.sum(c, axis = 1)) # rows

[228.  76. 158.]
[142. 164. 156.]


In [40]:
# Mininum value
print(c)
print(np.amin(c))
print(np.amin(c,axis=0))
print(np.amin(c,axis=1))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
1.0
[54.  1. 10.]
[25.  1. 10.]


In [41]:
# Maximum value
print(c)
print(np.amax(c))
print(np.amax(c,axis=0))
print(np.amax(c,axis=1))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
96.0
[96. 50. 85.]
[63. 85. 96.]


In [42]:
# Mean
print(c)
print(np.mean(c),'\n')
print(np.mean(c,axis=0),'\n')
print(np.mean(c,axis=1),'\n')
print(type(c))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
51.333333333333336 

[76.         25.33333333 52.66666667] 

[47.33333333 54.66666667 52.        ] 

<class 'numpy.ndarray'>


In [43]:
# Median
print(c)
print(np.median(c))
print(np.median(c,axis=0))
print(np.median(c,axis=1))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
54.0
[78. 25. 63.]
[54. 78. 50.]


In [44]:
# Standard deviation
print(c)
print(np.std(c))
print(np.std(c,axis=0))
print(np.std(c,axis=1))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
31.481917208313586
[17.20465053 20.00555478 31.47838765]
[16.21384868 38.055515   35.13782387]


In [45]:
# variance
print(c)
print(np.var(c))
print(np.var(c,axis=0))
print(np.var(c,axis=1))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
991.1111111111111
[296.         400.22222222 990.88888889]
[ 262.88888889 1448.22222222 1234.66666667]


In [46]:
# Weighted Average
print(np.average(c))

51.333333333333336


In [53]:
a = np.array([2,4,6,1,3,5,8,10,12,7,9,11])
print(a)

[ 2  4  6  1  3  5  8 10 12  7  9 11]


In [48]:
w = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5])
print(w)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5 ]


In [49]:
print(np.average(a, weights=w))

6.444444444444445


In [64]:
# percentile
print(c,'\n')
print(np.percentile(c,5),'\n')
print(np.percentile(c,5,0))
print(np.percentile(c,5,1))

[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]] 

4.6 

[56.4  3.4 15.3]
[27.9  8.7 14. ]


In [58]:
# peak to peak
print(c)
print(np.ptp(c,0))
print(np.ptp(c,1))
print('\n')
print(a)
print(np.ptp(a,0))


[[54. 25. 63.]
 [78.  1. 85.]
 [96. 50. 10.]]
[42. 49. 75.]
[38. 84. 86.]


[ 2  4  6  1  3  5  8 10 12  7  9 11]
11


In [67]:
# reshape of an array
x = np.array([[1,2,4,5],[8,7,9,6]])
print(x,'\n')
print(x.reshape(4,2),'\n')

[[1 2 4 5]
 [8 7 9 6]] 

[[1 2]
 [4 5]
 [8 7]
 [9 6]] 



# Slicing

In [65]:
# 2-D Array
l=np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l)

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]]


# Stacking

# Mathematical Operation